---
name: "MbedTLS-test"

on: [push, pull_request]

jobs:
  mbedtls:
    name: MbedTLS-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          # We must fetch at least the immediate parents so that if this is
          # a pull request then we can checkout the head.
          fetch-depth: 2
          submodules: 'recursive'

      - name: Installing MbedTLS
        run: |
             git clone https://github.com/Mbed-TLS/mbedtls
             cd mbedtls
             cmake --build .
             cd build
             make
             cd ../..

      - name: Compile picotls
        run: |
             cmake "-DWITH_MBEDTLS=ON" .
             make

      - name: Run test
        run: |
             ./test-mbedtls.t